global:
  scrape_interval:     10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: node_export
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: 'custom_metrics'
    #scrape_configs:
#  - job_name: 'metrics'
#    scrape_interval: 3s
#    static_configs:
    static_configs:
            - targets: ["localhost:80"]
    metrics_path: /prometheus.html